/** Kanban Projets — étape 2. Uses the real Projets schema from docs/grist_structure. */
(function () {
  'use strict';
  const COLUMNS=[{key:'Instruction',label:'Instruction',color:'#6941c6'},{key:'Notifications',label:'Notifications',color:'#1570ef'},{key:'Conventions',label:'Conventions',color:'#c11574'},{key:'Installation des fonds',label:'Installation des fonds',color:'#dc6803'},{key:'Projet en cours',label:'Projet en cours',color:'#039855'}];
  const text=v=>v==null?'':String(v), normalized=v=>text(v).trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''), tableRows=n=>(window.CoreState&&CoreState.getTable(n))||[], rowById=(n,id)=>tableRows(n).find(r=>String(r.id)===String(id)), refId=v=>v&&typeof v==='object'?v.id??v:v;
  const refLabel=(v,t,fields=[])=>{if(Array.isArray(v))return v.filter(x=>x!=='L').map(x=>refLabel(x,t,fields)).filter(Boolean).join(', ');const row=t&&v!=null&&v!==''?rowById(t,refId(v)):null,c=row||(v&&typeof v==='object'?v:null);if(c){for(const n of fields)if(c[n]!=null&&c[n]!=='')return text(c[n]);return text(c.NOM||c.nom_et_Prenom||c.name||c.label||c.Acronyme||c.id)}return v==null?'':text(v)};
  const valueLabel=(v,t,f)=>Array.isArray(v)?v.map(x=>refLabel(x,t,f)).filter(Boolean).join(', '):refLabel(v,t,f), programmeLabel=v=>valueLabel(v,'Programmes',['Programme']);
  const personLabel=v=>Array.isArray(v)?v.map(personLabel).filter(Boolean).join(', '):(rowById('Annuaire',refId(v))?text(rowById('Annuaire',refId(v)).nom_et_Prenom||[rowById('Annuaire',refId(v)).NOM,rowById('Annuaire',refId(v)).Prenom].filter(Boolean).join(' ')):text(v&&typeof v==='object'?(v.nom_et_Prenom||[v.NOM,v.Prenom].filter(Boolean).join(' ')||v.name||v.id):v));
  const instanceLabel=v=>Array.isArray(v)?v.map(instanceLabel).filter(Boolean).join(', '):((s=>s?refLabel(s,null,['Nom','name'])||valueLabel(s.Instance,'Instances',['Instances']):valueLabel(v,'Instances',['Instances']))(rowById('Suivi_Instance',refId(v))));
  const field=(p,n)=>{for(const x of n)if(p[x]!=null&&p[x]!=='')return p[x];return ''}, getProjects=()=>window.CoreState?.getTable('Projets')||[];
  function classifyStatus(p){const s=normalized(field(p,['Statut_Macro','Statut']));if(!s)return'Instruction';if(s.includes('notification')||s.includes('relecture')||s.includes('archive'))return'Notifications';if(s.includes('convention'))return'Conventions';if(s.includes('finance')||s.includes('fonds')||s.includes('gestionnaire'))return'Installation des fonds';return s.includes('instruction')||s.includes('pre-instruction')||s.includes('attente statut')?'Instruction':'Projet en cours'}
  function options(names,q=''){const inst=names.some(n=>['Instance_ratachee','Instance','Instances'].includes(n)),w=normalized(q);return[...new Set(getProjects().map(p=>text(inst?instanceLabel(field(p,names)):programmeLabel(field(p,names))).trim()).filter(v=>v&&v!=='0'&&normalized(v)!=='0'&&(!w||normalized(v).includes(w)))].sort((a,b)=>a.localeCompare(b,'fr'))}
  const comboValue=id=>document.getElementById(id)?.dataset.selectedValue||'';
  function currentFilters(){return{programme:comboValue('filter-programme'),instance:comboValue('filter-instance'),search:normalized(document.getElementById('filter-search')?.value)}}
  function filteredProjects(){const f=currentFilters();return getProjects().filter(p=>{const pr=programmeLabel(field(p,['Programme','Programme_Axe_InnovationS'])),ins=instanceLabel(field(p,['Instance_ratachee','Instance','Instances']));return(!f.programme||pr===f.programme)&&(!f.instance||ins===f.instance)&&(!f.search||normalized(text(p.Acronyme)).includes(f.search))})}
  const esc=v=>window.CoreUtils?.escapeHtml?CoreUtils.escapeHtml(text(v)):text(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function renderCombo(id,values,placeholder){const i=document.getElementById(id),l=document.getElementById(id+'-list');if(!i||!l)return;i.value=i.dataset.selectedValue||'';l.innerHTML=`<button type="button" data-value="">${esc(placeholder)}</button>`+values.map(v=>`<button type="button" data-value="${esc(v)}">${esc(v)}</button>`).join('');l.querySelectorAll('[data-value]').forEach(b=>b.addEventListener('mousedown',e=>{e.preventDefault();i.dataset.selectedValue=b.dataset.value;i.value=b.dataset.value;l.hidden=true;render()}))}
  function renderFilters(){renderCombo('filter-programme',options(['Programme','Programme_Axe_InnovationS']),'Tous les programmes');renderCombo('filter-instance',options(['Instance_ratachee','Instance','Instances']),'Toutes les instances')}
  function card(p){const h=personLabel(field(p,['Porteur_1','Porteur','porteur_1']))||'Porteur non renseigné',a=personLabel(field(p,['Accompagnateur']))||'Accompagnateur non renseigné',pr=programmeLabel(field(p,['Programme','Programme_Axe_InnovationS'])),st=valueLabel(field(p,['Statut_operationnel_projet','Conventions_statut','Statut_Financier']))||'Statut macro non renseigné',co=!!p.Convention_de_reversement||!!p.Convention_de_reversement_le_cas_echeant;return`<button type="button" class="project-card" data-project-id="${esc(p.id)}"><span class="project-acronym">${esc(p.Acronyme||'Sans acronyme')}</span>${pr?`<span class="programme-badge">${esc(pr)}</span>`:''}<span class="project-holder"><strong>Porteur :</strong> ${esc(h)}</span><span class="project-holder"><strong>Accompagnateur :</strong> ${esc(a)}</span><span class="project-substatus"><strong>Statut macro :</strong> ${esc(st)}</span>${co?'<span class="convention-badge">Convention</span>':''}</button>`}
  function render(){const b=document.getElementById('projects-kanban');if(!b)return;const ps=filteredProjects();b.innerHTML=COLUMNS.map(c=>{const cards=ps.filter(p=>classifyStatus(p)===c.key);return`<section class="kanban-column" style="--column-accent:${c.color}" aria-labelledby="kanban-${normalized(c.key)}"><header class="kanban-column-header"><h3 id="kanban-${normalized(c.key)}">${c.label}</h3><span class="kanban-count">${cards.length}</span></header><div class="kanban-cards">${cards.length?cards.map(card).join(''):'<p class="kanban-empty">Aucun projet</p>'}</div></section>`}).join('');b.querySelectorAll('[data-project-id]').forEach(e=>e.addEventListener('click',()=>{const p=getProjects().find(x=>String(x.id)===String(e.dataset.projectId));if(p&&window.ProjectModal?.open)ProjectModal.open(p);else if(window.openProject)openProject(e.dataset.projectId);else if(typeof viewProject==='function')viewProject(Number(e.dataset.projectId))}))}
  function setupCombo(id,names,placeholder){const i=document.getElementById(id),l=document.getElementById(id+'-list');if(!i||!l)return;i.addEventListener('focus',()=>{l.hidden=false;renderCombo(id,options(names,i.value),placeholder)});i.addEventListener('input',()=>{i.dataset.selectedValue='';l.hidden=false;renderCombo(id,options(names,i.value),placeholder)});i.addEventListener('blur',()=>setTimeout(()=>{l.hidden=true;if(!i.dataset.selectedValue)i.value=''},150))}
  function init(){renderFilters();setupCombo('filter-programme',['Programme','Programme_Axe_InnovationS'],'Tous les programmes');setupCombo('filter-instance',['Instance_ratachee','Instance','Instances'],'Toutes les instances');render();document.getElementById('filter-search')?.addEventListener('input',render);document.getElementById('clear-filters')?.addEventListener('click',()=>{['filter-programme','filter-instance'].forEach(id=>{const e=document.getElementById(id);if(e){e.value='';e.dataset.selectedValue=''}});const s=document.getElementById('filter-search');if(s)s.value='';renderFilters();render()})}
  window.renderProjectsKanban=()=>{renderFilters();render()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
}());