/* Création de projet — composant modal fonctionnel. */
(function (global) {
  'use strict';

  const text = v => v == null ? '' : String(v);
  const rows = name => tables()?.getTable(name) || [];
  const tables = () => global.CoreState && typeof global.CoreState.getTable === 'function' ? { getTable: name => global.CoreState.getTable(name) } : global.CoreGrist?.tables;
  const esc = v => text(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const label = (r, fields) => fields.map(k => r?.[k]).find(v => v != null && v !== '') || '';
  const personLabel = r => label(r, ['nom_et_Prenom', 'Prenom', 'NOM']);
  const opeLabel = r => text(r?.N_OPE);
  const FIN = {2026:['c2026_M10_Fonctionnement','c2026_M20_Investissement','c2026_M30_Personnel'],2027:['c2027_M10_Fonctionnement','c2027_M20_Investissement','c2027_M30_Personnel'],2028:['c2028_M10_Fonctionnement','c2028_M20_Investissement','c2028_M30_Personnel']};
  function updateFinancialTotals(table){ Object.entries(FIN).forEach(([year,keys])=>{ const total=keys.reduce((sum,key)=>sum+(Number(table.querySelector(`[data-fin="${key}"]`)?.value)||0),0); table.querySelector(`[data-total="${year}"]`).textContent=total.toLocaleString("fr-FR"); }); table.querySelectorAll('tbody tr[data-detail]').forEach(tr=>{ const total=[...tr.querySelectorAll('[data-fin]')].reduce((sum,input)=>sum+(Number(input.value)||0),0); tr.querySelector('[data-row-total]').textContent=total.toLocaleString("fr-FR"); }); const grand=[...table.querySelectorAll('tbody [data-fin]')].reduce((sum,input)=>sum+(Number(input.value)||0),0); table.querySelector('[data-grand-total]').textContent=grand.toLocaleString("fr-FR"); }
  function refField(parent,key,table,display,required=false){const wrap=document.createElement('div');wrap.className='cp-field cp-ref';wrap.innerHTML=`<label>${esc(display.label)}${required?' *':''}</label><input autocomplete="off" data-ref="${key}" placeholder="Rechercher…"><div class="cp-ref-list cp-hidden"></div>`;const input=wrap.querySelector('input'),list=wrap.querySelector('.cp-ref-list');const all=()=>table==='__choice__'?[]:rows(table);const displayValue=r=>text(display.format?display.format(r):label(r,display.fields));const render=()=>{input.dataset.id='';const q=input.value.trim().toLowerCase();list.innerHTML=all().filter(r=>displayValue(r).toLowerCase().includes(q)).slice(0,30).map(r=>`<button type="button" data-id="${esc(r.id)}">${esc(displayValue(r))}</button>`).join('');list.classList.toggle('cp-hidden',!list.innerHTML);list.querySelectorAll('button').forEach(b=>b.onclick=()=>{input.value=b.textContent;input.dataset.id=b.dataset.id;list.classList.add('cp-hidden');});};input.oninput=render;input.onfocus=render;input.onblur=()=>setTimeout(()=>list.classList.add('cp-hidden'),150);parent.appendChild(wrap);return {wrap,input};}
  function field(parent,labelText,id,type='text',required=false){const w=document.createElement('div');w.className='cp-field';w.innerHTML=`<label for="${id}">${esc(labelText)}${required?' *':''}</label><input id="${id}" type="${type}">`;parent.appendChild(w);return w.querySelector('input');}
  function setRef(ref,value,tableName,displayFields){if(!ref)return;const id=value&&typeof value==='object'?value.id:value;const found=id!=null?rows(tableName).find(r=>String(r.id)===String(id)):null;ref.input.dataset.id=id==null?'':String(id);ref.input.value=found?label(found,displayFields):text(value);}
  function createModal(){if(document.getElementById('cp-project-modal'))return document.getElementById('cp-project-modal');const m=document.createElement('div');m.id='cp-project-modal';m.className='cp-modal cp-hidden';m.innerHTML=`<div class="cp-box"><h2>Créer un projet</h2><div id="cp-project-form" class="cp-grid"></div><button data-cp-save>Créer le projet</button></div>`;document.body.appendChild(m);const f=m.querySelector('#cp-project-form');const refs={};refs.programme=refField(f,'Programme','Programmes',{label:'Programme',fields:['Programme']},true);field(f,'Projet','cp-Projet','text',true);field(f,'Acronyme','cp-Acronyme','text',true);refs.Porteur_1=refField(f,'Porteur_1','Annuaire',{label:'Porteur 1',fields:['nom_et_Prenom','Prenom','NOM']},true);refs.tutelle=refField(f,'Tutelle','Etablissements',{label:'Tutelle du porteur',fields:['Acronyme','Nom_complet','acronyme','Nom']});const table=document.createElement('table');table.className='cp-fin';table.innerHTML='<tbody><tr data-detail="Details_depense_s_Fonctionnement"><th>Fonctionnement</th><td></td><td></td><td></td><td data-row-total="Details_depense_s_Fonctionnement">0</td></tr><tr data-detail="Details_depense_s_Investissement"><th>Investissement</th><td></td><td></td><td></td><td data-row-total="Details_depense_s_Investissement">0</td></tr><tr data-detail="Details_depense_s_Personnel"><th>Personnel</th><td></td><td></td><td></td><td data-row-total="Details_depense_s_Personnel">0</td></tr></tbody><tfoot><tr><td data-total="2026">0</td><td data-total="2027">0</td><td data-total="2028">0</td><td data-grand-total>0</td></tr></tfoot>';Object.entries(FIN).forEach(([year,fs])=>table.querySelectorAll('tbody tr').forEach((tr,i)=>{const input=document.createElement('input');input.type='number';input.min='0';input.step='any';input.value='0';input.dataset.fin=fs[i];input.oninput=()=>updateFinancialTotals(table);tr.children[Number(year)-2025].appendChild(input);}));f.appendChild(table);m._refs=refs;m.querySelector('[data-cp-save]').onclick=()=>saveProject(m,refs);return m;}
  function collectFields(m,refs){const fields={Programme:Number(refs.programme.input.dataset.id),Projet:m.querySelector('#cp-Projet').value.trim(),Acronyme:m.querySelector('#cp-Acronyme').value.trim(),Porteur_1:Number(refs.Porteur_1.input.dataset.id),Tutelle:Number(refs.tutelle.input.dataset.id)||null};m.querySelectorAll('[data-fin]').forEach(i=>{const value=Number(i.value);fields[i.dataset.fin]=Number.isFinite(value)?value:0;});return global.CoreGrist?.normaliseProjectFields?global.CoreGrist.normaliseProjectFields(fields):fields;}
  async function saveProject(m,refs){const fields=collectFields(m,refs);const api=global.CoreGrist?.gristInstance;if(!api)throw new Error('API Grist indisponible');await api.docApi.applyUserActions([['AddRecord','Projets',null,fields]]);}
  global.ProjectModal={open(){return createModal();}};
})(window);
